<?php

namespace Database\Seeders;

use App\Models\TimeZone;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TimeZoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    private $timezones = array(
        array('name' => 'Pacific/Midway','location' => '(GMT-11:00) Midway Island'),
        array('name' => 'US/Samoa','location' => '(GMT-11:00) Samoa'),
        array('name' => 'US/Hawaii','location' => '(GMT-10:00) Hawaii'),
        array('name' => 'US/Alaska','location' => '(GMT-09:00) Alaska'),
        array('name' => 'US/Pacific','location' => '(GMT-08:00) Pacific Time (US &amp; Canada)'),
        array('name' => 'America/Tijuana','location' => '(GMT-08:00) Tijuana'),
        array('name' => 'US/Arizona','location' => '(GMT-07:00) Arizona'),
        array('name' => 'US/Mountain','location' => '(GMT-07:00) Mountain Time (US &amp; Canada)'),
        array('name' => 'America/Chihuahua','location' => '(GMT-07:00) Chihuahua'),
        array('name' => 'America/Mazatlan','location' => '(GMT-07:00) Mazatlan'),
        array('name' => 'America/Mexico_City','location' => '(GMT-06:00) Mexico City'),
        array('name' => 'America/Monterrey','location' => '(GMT-06:00) Monterrey'),
        array('name' => 'Canada/Saskatchewan','location' => '(GMT-06:00) Saskatchewan'),
        array('name' => 'US/Central','location' => '(GMT-06:00) Central Time (US &amp; Canada)'),
        array('name' => 'US/Eastern','location' => '(GMT-05:00) Eastern Time (US &amp; Canada)'),
        array('name' => 'US/East-Indiana','location' => '(GMT-05:00) Indiana (East)'),
        array('name' => 'America/Bogota','location' => '(GMT-05:00) Bogota'),
        array('name' => 'America/Lima','location' => '(GMT-05:00) Lima'),
        array('name' => 'America/Caracas','location' => '(GMT-04:30) Caracas'),
        array('name' => 'Canada/Atlantic','location' => '(GMT-04:00) Atlantic Time (Canada)'),
        array('name' => 'America/La_Paz','location' => '(GMT-04:00) La Paz'),
        array('name' => 'America/Santiago','location' => '(GMT-04:00) Santiago'),
        array('name' => 'Canada/Newfoundland','location' => '(GMT-03:30) Newfoundland'),
        array('name' => 'America/Buenos_Aires','location' => '(GMT-03:00) Buenos Aires'),
        array('name' => 'Greenland','location' => '(GMT-03:00) Greenland'),
        array('name' => 'Atlantic/Stanley','location' => '(GMT-02:00) Stanley'),
        array('name' => 'Atlantic/Azores','location' => '(GMT-01:00) Azores'),
        array('name' => 'Atlantic/Cape_Verde','location' => '(GMT-01:00) Cape Verde Is.'),
        array('name' => 'Africa/Casablanca','location' => '(GMT) Casablanca'),
        array('name' => 'Europe/Dublin','location' => '(GMT) Dublin'),
        array('name' => 'Europe/Lisbon','location' => '(GMT) Lisbon'),
        array('name' => 'Europe/London','location' => '(GMT) London'),
        array('name' => 'Africa/Monrovia','location' => '(GMT) Monrovia'),
        array('name' => 'Europe/Amsterdam','location' => '(GMT+01:00) Amsterdam'),
        array('name' => 'Europe/Belgrade','location' => '(GMT+01:00) Belgrade'),
        array('name' => 'Europe/Berlin','location' => '(GMT+01:00) Berlin'),
        array('name' => 'Europe/Bratislava','location' => '(GMT+01:00) Bratislava'),
        array('name' => 'Europe/Brussels','location' => '(GMT+01:00) Brussels'),
        array('name' => 'Europe/Budapest','location' => '(GMT+01:00) Budapest'),
        array('name' => 'Europe/Copenhagen','location' => '(GMT+01:00) Copenhagen'),
        array('name' => 'Europe/Ljubljana','location' => '(GMT+01:00) Ljubljana'),
        array('name' => 'Europe/Madrid','location' => '(GMT+01:00) Madrid'),
        array('name' => 'Europe/Paris','location' => '(GMT+01:00) Paris'),
        array('name' => 'Europe/Prague','location' => '(GMT+01:00) Prague'),
        array('name' => 'Europe/Rome','location' => '(GMT+01:00) Rome'),
        array('name' => 'Europe/Sarajevo','location' => '(GMT+01:00) Sarajevo'),
        array('name' => 'Europe/Skopje','location' => '(GMT+01:00) Skopje'),
        array('name' => 'Europe/Stockholm','location' => '(GMT+01:00) Stockholm'),
        array('name' => 'Europe/Vienna','location' => '(GMT+01:00) Vienna'),
        array('name' => 'Europe/Warsaw','location' => '(GMT+01:00) Warsaw'),
        array('name' => 'Europe/Zagreb','location' => '(GMT+01:00) Zagreb'),
        array('name' => 'Europe/Athens','location' => '(GMT+02:00) Athens'),
        array('name' => 'Europe/Bucharest','location' => '(GMT+02:00) Bucharest'),
        array('name' => 'Africa/Cairo','location' => '(GMT+02:00) Cairo'),
        array('name' => 'Africa/Harare','location' => '(GMT+02:00) Harare'),
        array('name' => 'Europe/Helsinki','location' => '(GMT+02:00) Helsinki'),
        array('name' => 'Europe/Istanbul','location' => '(GMT+02:00) Istanbul'),
        array('name' => 'Asia/Jerusalem','location' => '(GMT+02:00) Jerusalem'),
        array('name' => 'Europe/Kiev','location' => '(GMT+02:00) Kyiv'),
        array('name' => 'Europe/Minsk','location' => '(GMT+02:00) Minsk'),
        array('name' => 'Europe/Riga','location' => '(GMT+02:00) Riga'),
        array('name' => 'Europe/Sofia','location' => '(GMT+02:00) Sofia'),
        array('name' => 'Europe/Tallinn','location' => '(GMT+02:00) Tallinn'),
        array('name' => 'Europe/Vilnius','location' => '(GMT+02:00) Vilnius'),
        array('name' => 'Asia/Baghdad','location' => '(GMT+03:00) Baghdad'),
        array('name' => 'Asia/Kuwait','location' => '(GMT+03:00) Kuwait'),
        array('name' => 'Africa/Nairobi','location' => '(GMT+03:00) Nairobi'),
        array('name' => 'Asia/Riyadh','location' => '(GMT+03:00) Riyadh'),
        array('name' => 'Asia/Tehran','location' => '(GMT+03:30) Tehran'),
        array('name' => 'Europe/Moscow','location' => '(GMT+04:00) Moscow'),
        array('name' => 'Asia/Baku','location' => '(GMT+04:00) Baku'),
        array('name' => 'Europe/Volgograd','location' => '(GMT+04:00) Volgograd'),
        array('name' => 'Asia/Muscat','location' => '(GMT+04:00) Muscat'),
        array('name' => 'Asia/Tbilisi','location' => '(GMT+04:00) Tbilisi'),
        array('name' => 'Asia/Yerevan','location' => '(GMT+04:00) Yerevan'),
        array('name' => 'Asia/Kabul','location' => '(GMT+04:30) Kabul'),
        array('name' => 'Asia/Karachi','location' => '(GMT+05:00) Karachi'),
        array('name' => 'Asia/Tashkent','location' => '(GMT+05:00) Tashkent'),
        array('name' => 'Asia/Kolkata','location' => '(GMT+05:30) Kolkata'),
        array('name' => 'Asia/Kathmandu','location' => '(GMT+05:45) Kathmandu'),
        array('name' => 'Asia/Yekaterinburg','location' => '(GMT+06:00) Ekaterinburg'),
        array('name' => 'Asia/Almaty','location' => '(GMT+06:00) Almaty'),
        array('name' => 'Asia/Dhaka','location' => '(GMT+06:00) Dhaka'),
        array('name' => 'Asia/Novosibirsk','location' => '(GMT+07:00) Novosibirsk'),
        array('name' => 'Asia/Bangkok','location' => '(GMT+07:00) Bangkok'),
        array('name' => 'Asia/Jakarta','location' => '(GMT+07:00) Jakarta'),
        array('name' => 'Asia/Krasnoyarsk','location' => '(GMT+08:00) Krasnoyarsk'),
        array('name' => 'Asia/Chongqing','location' => '(GMT+08:00) Chongqing'),
        array('name' => 'Asia/Hong_Kong','location' => '(GMT+08:00) Hong Kong'),
        array('name' => 'Asia/Kuala_Lumpur','location' => '(GMT+08:00) Kuala Lumpur'),
        array('name' => 'Australia/Perth','location' => '(GMT+08:00) Perth'),
        array('name' => 'Asia/Singapore','location' => '(GMT+08:00) Singapore'),
        array('name' => 'Asia/Taipei','location' => '(GMT+08:00) Taipei'),
        array('name' => 'Asia/Ulaanbaatar','location' => '(GMT+08:00) Ulaan Bataar'),
        array('name' => 'Asia/Urumqi','location' => '(GMT+08:00) Urumqi'),
        array('name' => 'Asia/Irkutsk','location' => '(GMT+09:00) Irkutsk'),
        array('name' => 'Asia/Seoul','location' => '(GMT+09:00) Seoul'),
        array('name' => 'Asia/Tokyo','location' => '(GMT+09:00) Tokyo'),
        array('name' => 'Australia/Adelaide','location' => '(GMT+09:30) Adelaide'),
        array('name' => 'Australia/Darwin','location' => '(GMT+09:30) Darwin'),
        array('name' => 'Asia/Yakutsk','location' => '(GMT+10:00) Yakutsk'),
        array('name' => 'Australia/Brisbane','location' => '(GMT+10:00) Brisbane'),
        array('name' => 'Australia/Canberra','location' => '(GMT+10:00) Canberra'),
        array('name' => 'Pacific/Guam','location' => '(GMT+10:00) Guam'),
        array('name' => 'Australia/Hobart','location' => '(GMT+10:00) Hobart'),
        array('name' => 'Australia/Melbourne','location' => '(GMT+10:00) Melbourne'),
        array('name' => 'Pacific/Port_Moresby','location' => '(GMT+10:00) Port Moresby'),
        array('name' => 'Australia/Sydney','location' => '(GMT+10:00) Sydney'),
        array('name' => 'Asia/Vladivostok','location' => '(GMT+11:00) Vladivostok'),
        array('name' => 'Asia/Magadan','location' => '(GMT+12:00) Magadan'),
        array('name' => 'Pacific/Auckland','location' => '(GMT+12:00) Auckland'),
        array('name' => 'Pacific/Fiji','location' => '(GMT+12:00) Fiji')
    );
    public function run()
    {
        TimeZone::insert($this->timezones);
    }
}
